---

- name: Create Arista Primary Port
  hosts: arista

  tasks:

    - name: create vlan666
      eos_vlan: name=vlan666 vlanid=666
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: create vlan667
      eos_vlan: name=vlan667 vlanid=667
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: create vlan668
      eos_vlan: name=vlan668 vlanid=668
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https



    - name: set Ethernet3 description
      eos_interface: name=Ethernet3 description="XXX IN USE XXX"
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: Configure trunk on Ethernet3
      eos_switchport: name=Ethernet3 mode=trunk trunk_allowed_vlans=666,667,668 trunk_native_vlan=1
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https
