---

- name: Create Arista Primary Port
  hosts: arista

  tasks:

    - name: remove vlan666
      eos_vlan: name=vlan666 vlanid=666 state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: remove vlan667
      eos_vlan: name=vlan667 vlanid=667 state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: remove vlan668
      eos_vlan: name=vlan668 vlanid=668 state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https



    - name: clear Ethernet3 description
      eos_interface: name=Ethernet3 description=
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: de-configure trunk on Ethernet3
      eos_switchport: name=Ethernet3 mode='access'
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: set trunk allowed vlans to default
      eos_switchport: name=Ethernet3 trunk_allowed_vlans=1-4094
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https


