---

- name: Create Arista Primary Port
  hosts: arista

  tasks:

    - name: remove vlan666
      eos_vlan: name=vlan666 vlanid=666 state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: remove Ethernet3 description
      eos_interface: name=Ethernet3 description=
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

    - name: deassign vlan to access port Ethernet3
      eos_switchport: name=Ethernet3 access_vlan=
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https

